<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DEEP-1808222042" ignored="0" name="Test" tests="7" failures="1" timestamp="30 五月 2019 16:00:00 GMT" time="120.905" errors="0">
  <testcase name="testLoginfail" time="34.245" classname="com.test.ng.TestLoginFail"/>
  <testcase name="deleteMail" time="36.552" classname="com.test.ng.DeleteMail">
    <skipped/>
  </testcase> <!-- deleteMail -->
  <testcase name="login" time="25.947" classname="com.test.ng.LoginTestNG"/>
  <testcase name="deleteMail" time="24.627" classname="com.test.ng.DeleteMail">
    <skipped/>
  </testcase> <!-- deleteMail -->
  <testcase name="deleteMail" time="17.727" classname="com.test.ng.DeleteMail">
    <skipped/>
  </testcase> <!-- deleteMail -->
  <testcase name="createMail" time="29.884" classname="com.test.ng.CreateAndSendMail"/>
  <testcase name="deleteMail" time="9.699" classname="com.test.ng.DeleteMail">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 1, Size: 1">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.ArrayList.rangeCheck(ArrayList.java:653)
at java.util.ArrayList.get(ArrayList.java:429)
at com.test.ng.DeleteMail.deleteMail(DeleteMail.java:65)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- deleteMail -->
</testsuite> <!-- Test -->
