<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="4" failed="1" ignored="0" total="8" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="220653" started-at="2019-05-30T14:44:54Z" finished-at="2019-05-30T14:48:34Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="220653" started-at="2019-05-30T14:44:54Z" finished-at="2019-05-30T14:48:34Z">
      <class name="com.test.ng.TestLoginFail">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.test.ng.TestLoginFail@291ae]" name="setUp" is-config="true" duration-ms="25959" started-at="2019-05-30T14:44:54Z" finished-at="2019-05-30T14:45:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testLoginfail()[pri:0, instance:com.test.ng.TestLoginFail@291ae]" name="testLoginfail" duration-ms="55718" started-at="2019-05-30T14:45:20Z" finished-at="2019-05-30T14:46:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoginfail -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.test.ng.TestLoginFail@291ae]" name="tearDown" is-config="true" duration-ms="3428" started-at="2019-05-30T14:46:15Z" finished-at="2019-05-30T14:46:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.test.ng.TestLoginFail -->
      <class name="com.test.ng.CreateAndSendMail">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.test.ng.CreateAndSendMail@50eac852]" name="setUp" is-config="true" duration-ms="3075" started-at="2019-05-30T14:47:14Z" finished-at="2019-05-30T14:47:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="createMail()[pri:0, instance:com.test.ng.CreateAndSendMail@50eac852]" name="createMail" duration-ms="48734" started-at="2019-05-30T14:47:17Z" finished-at="2019-05-30T14:48:06Z">
          <exception class="org.openqa.selenium.NoSuchElementException">
            <message>
              <![CDATA[no such element: Unable to locate element: {"method":"xpath","selector":"//h1[text()='发送成功']"}
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.10586 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 10.05 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40'
System info: host: 'DEEP-1808222042', ip: '169.254.25.116', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_101'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{mobileEmulationEnabled=false, hasTouchScreen=false, platform=XP, acceptSslCerts=false, goog:chromeOptions={debuggerAddress=localhost:35135}, acceptInsecureCerts=false, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, setWindowRect=true, unexpectedAlertBehaviour=, applicationCacheEnabled=false, rotatable=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e), userDataDir=C:\Users\ADMINI~1\AppData\Local\Temp\scoped_dir8708_30811}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, version=68.0.3440.84, browserConnectionEnabled=false, nativeEvents=true, locationContextEnabled=true, cssSelectorsEnabled=true}]
Session ID: 8c7a7795c4e181adae74d52d04823aaf]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//h1[text()='发送成功']"}
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.10586 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 10.05 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40'
System info: host: 'DEEP-1808222042', ip: '169.254.25.116', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_101'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{mobileEmulationEnabled=false, hasTouchScreen=false, platform=XP, acceptSslCerts=false, goog:chromeOptions={debuggerAddress=localhost:35135}, acceptInsecureCerts=false, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, setWindowRect=true, unexpectedAlertBehaviour=, applicationCacheEnabled=false, rotatable=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e), userDataDir=C:\Users\ADMINI~1\AppData\Local\Temp\scoped_dir8708_30811}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, version=68.0.3440.84, browserConnectionEnabled=false, nativeEvents=true, locationContextEnabled=true, cssSelectorsEnabled=true}]
Session ID: 8c7a7795c4e181adae74d52d04823aaf
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:449)
at org.openqa.selenium.By$ByXPath.findElement(By.java:357)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
at com.test.ng.CreateAndSendMail.createMail(CreateAndSendMail.java:102)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchElementException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createMail -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.test.ng.CreateAndSendMail@50eac852]" name="tearDown" is-config="true" duration-ms="3207" started-at="2019-05-30T14:48:06Z" finished-at="2019-05-30T14:48:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.test.ng.CreateAndSendMail@50eac852]" name="setUp" is-config="true" duration-ms="2587" started-at="2019-05-30T14:48:09Z" finished-at="2019-05-30T14:48:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="createMail()[pri:0, instance:com.test.ng.CreateAndSendMail@50eac852]" name="createMail" duration-ms="19405" started-at="2019-05-30T14:48:12Z" finished-at="2019-05-30T14:48:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createMail -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.test.ng.CreateAndSendMail@50eac852]" name="tearDown" is-config="true" duration-ms="3174" started-at="2019-05-30T14:48:31Z" finished-at="2019-05-30T14:48:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.test.ng.CreateAndSendMail -->
      <class name="com.test.ng.DeleteMail">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.test.ng.DeleteMail@243c4f91]" name="setUp" is-config="true" duration-ms="25959" started-at="2019-05-30T14:44:54Z" finished-at="2019-05-30T14:45:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="deleteMail()[pri:0, instance:com.test.ng.DeleteMail@243c4f91]" name="deleteMail" duration-ms="73737" started-at="2019-05-30T14:45:20Z" finished-at="2019-05-30T14:46:33Z">
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index: 1, Size: 1]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.ArrayList.rangeCheck(ArrayList.java:653)
at java.util.ArrayList.get(ArrayList.java:429)
at com.test.ng.DeleteMail.deleteMail(DeleteMail.java:65)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteMail -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.test.ng.DeleteMail@243c4f91]" name="tearDown" is-config="true" duration-ms="3166" started-at="2019-05-30T14:46:33Z" finished-at="2019-05-30T14:46:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.test.ng.DeleteMail@243c4f91]" name="setUp" is-config="true" duration-ms="3282" started-at="2019-05-30T14:46:37Z" finished-at="2019-05-30T14:46:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="deleteMail()[pri:0, instance:com.test.ng.DeleteMail@243c4f91]" name="deleteMail" duration-ms="34516" started-at="2019-05-30T14:46:40Z" finished-at="2019-05-30T14:47:14Z">
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index: 1, Size: 1]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.ArrayList.rangeCheck(ArrayList.java:653)
at java.util.ArrayList.get(ArrayList.java:429)
at com.test.ng.DeleteMail.deleteMail(DeleteMail.java:65)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteMail -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.test.ng.DeleteMail@243c4f91]" name="tearDown" is-config="true" duration-ms="3654" started-at="2019-05-30T14:47:14Z" finished-at="2019-05-30T14:47:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.test.ng.DeleteMail@243c4f91]" name="setUp" is-config="true" duration-ms="2913" started-at="2019-05-30T14:47:18Z" finished-at="2019-05-30T14:47:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="deleteMail()[pri:0, instance:com.test.ng.DeleteMail@243c4f91]" name="deleteMail" duration-ms="27129" started-at="2019-05-30T14:47:21Z" finished-at="2019-05-30T14:47:48Z">
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index: 1, Size: 1]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.ArrayList.rangeCheck(ArrayList.java:653)
at java.util.ArrayList.get(ArrayList.java:429)
at com.test.ng.DeleteMail.deleteMail(DeleteMail.java:65)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteMail -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.test.ng.DeleteMail@243c4f91]" name="tearDown" is-config="true" duration-ms="3129" started-at="2019-05-30T14:47:48Z" finished-at="2019-05-30T14:47:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.test.ng.DeleteMail@243c4f91]" name="setUp" is-config="true" duration-ms="2996" started-at="2019-05-30T14:47:51Z" finished-at="2019-05-30T14:47:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="deleteMail()[pri:0, instance:com.test.ng.DeleteMail@243c4f91]" name="deleteMail" duration-ms="15093" started-at="2019-05-30T14:47:54Z" finished-at="2019-05-30T14:48:09Z">
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index: 1, Size: 1]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.ArrayList.rangeCheck(ArrayList.java:653)
at java.util.ArrayList.get(ArrayList.java:429)
at com.test.ng.DeleteMail.deleteMail(DeleteMail.java:65)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteMail -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.test.ng.DeleteMail@243c4f91]" name="tearDown" is-config="true" duration-ms="3210" started-at="2019-05-30T14:48:09Z" finished-at="2019-05-30T14:48:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.test.ng.DeleteMail -->
      <class name="com.test.ng.LoginTestNG">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.test.ng.LoginTestNG@61df66b6]" name="beforeMethod" is-config="true" duration-ms="10611" started-at="2019-05-30T14:46:19Z" finished-at="2019-05-30T14:46:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="login()[pri:0, instance:com.test.ng.LoginTestNG@61df66b6]" name="login" duration-ms="43342" started-at="2019-05-30T14:46:30Z" finished-at="2019-05-30T14:47:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.test.ng.LoginTestNG@61df66b6]" name="afterMethod" is-config="true" duration-ms="1092" started-at="2019-05-30T14:47:13Z" finished-at="2019-05-30T14:47:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.test.ng.LoginTestNG -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
